# Change these first
owner: cryptohslu # Your GitHub organization or username, where this repository lives
repo: statuspage # The name of this repository

assignees:
  - iyanmv

sites:
  - name: reproducible.crypto-lab.ch
    url: https://reproducible.crypto-lab.ch/
    __dangerous__body_degraded_if_text_missing: "Reproducible Builds"
  - name: HSLU drand relay
    url: https://drand.crypto-lab.ch/v2/beacons/quicknet/info
    icon: https://drive.switch.ch/index.php/s/d5jsAkauQUhsU2M/download
    __dangerous__body_degraded_if_text_missing: "quicknet"
  - name: PQC info website
    url: https://pqc.crypto-lab.ch
    __dangerous__body_degraded_if_text_missing: "PQC visualizations"
  - name: PQC Digital Signatures
    url: https://pqc.crypto-lab.ch/sig-charts/
    __dangerous__body_degraded_if_text_missing: "Dash"
  - name: PQC TLS
    url: https://pqc.crypto-lab.ch/tls-charts/
    __dangerous__body_degraded_if_text_missing: "Dash"
  - name: PQC Matrix server
    url: https://matrix.crypto-lab.ch
    __dangerous__body_degraded_if_text_missing: "Element"
  - name: randextract.crypto-lab.ch
    url: https://randextract.crypto-lab.ch/
    __dangerous__body_degraded_if_text_missing: "RandExtract"
  - name: QRNG
    url: $QRNG_URL
  - name: dice1.drand.ch
    url: https://dice1.drand.ch/
    headers:
      - "Authorization: Basic $TLS_WEBAPP_AUTH"
      - "Content-Type: application/json"
  - name: dice2.drand.ch
    url: https://dice2.drand.ch/
    headers:
      - "Authorization: Basic $TLS_WEBAPP_AUTH"
      - "Content-Type: application/json"
  - name: dice3.drand.ch
    url: https://dice3.drand.ch/
    headers:
      - "Authorization: Basic $TLS_WEBAPP_AUTH"
      - "Content-Type: application/json"
  - name: TURN server
    url: https://turn.crypto-lab.ch/health
  - name: hslu.ch/en/acs
    url: https://www.hslu.ch/en/acs

status-website:
  cname: status.drand.ch
  logoUrl: https://status.drand.ch/upptime-icon.svg
  # themeUrl: https://status.drand.ch/hslu-theme.css
  name: Upptime
  introTitle: "**Applied Cyber Security Research Lab **"
  introMessage: Uptime monitor and status page from our public websites and services. This site is generated with real-time data from our [GitHub repository](https://github.com/cryptohslu/statuspage) using the free and open-source tool [Upptime](https://upptime.js.org/).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Applied Cyber Security Research Lab
      href: https://www.hslu.ch/en/acs

i18n:
  footer: "Applied Cyber Security Research Lab © 2026"
