# Change these first
owner: cryptohslu # Your GitHub organization or username, where this repository lives
repo: statuspage # The name of this repository

sites:
  - name: reproducible.crypto-lab.ch
    url: https://reproducible.crypto-lab.ch/
  - name: PQC info website
    url: https://pqc.crypto-lab.ch
  - name: PQC Digital Signatures
    url: https://pqc.crypto-lab.ch/sig-charts/
  - name: PQC TLS
    url: https://pqc.crypto-lab.ch/tls-charts/
    headers:
      - "Authorization: Basic $DICE_AUTH"
      - "Content-Type: application/json"
  - name: randextract.crypto-lab.ch
    url: https://randextract.crypto-lab.ch/
  - name: QRNG
    url: $QRNG_URL
  - name: dice.drand.ch
    url: https://dice.drand.ch/
    headers:
      - "Authorization: Basic $TLS_WEBAPP_AUTH"
      - "Content-Type: application/json"
  - name: hslu.ch/en/acs
    url: https://www.hslu.ch/en/acs

status-website:
  cname: status.drand.ch
  logoUrl: https://status.drand.ch/upptime-icon.svg
  # themeUrl: https://status.drand.ch/hslu-theme.css
  name: Upptime
  introTitle: "**Applied Cyber Security Research Lab **"
  introMessage: Uptime monitor and status page from our public websites and services. This site is generated with real-time data from our [GitHub repository](https://github.com/cryptohslu/statuspage) using the free and open-source tool [Upptime](https://upptime.js.org/).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Applied Cyber Security Research Lab
      href: https://www.hslu.ch/en/acs

i18n:
  footer: "Applied Cyber Security Research Lab © 2025"


assignees:
  - iyanmv

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
