# Change these first
owner: cryptohslu # Your GitHub organization or username, where this repository lives
repo: statuspage # The name of this repository

sites:
  - name: reproducible.crypto-lab.ch
    url: https://reproducible.crypto-lab.ch/
  - name: pqc.crypto-lab.ch
    check: "tcp-ping"
    url: pqc.crypto-lab.ch
    port: 443
  - name: randextract.crypto-lab.ch
    url: https://randextract.crypto-lab.ch/
  - name: www.hslu.ch/en/acs
    url: https://www.hslu.ch/en/acs

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.drand.ch
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/cryptohslu/statuspage/refs/heads/master/assets/hslu-acs-logo.png
  # name: Upptime
  introTitle: "**Applied Cyber Security Research Lab **"
  introMessage: Uptime monitor and status page from our public websites and services. This site is generated with real-time data from our [GitHub repository](https://github.com/cryptohslu/statuspage) using the free and open-source tool [Upptime](https://upptime.js.org/).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Applied Cyber Security Research Lab
      href: https://www.hslu.ch/en/acs

i18n:
  footer: "Applied Cyber Security Research Lab © 2025"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
